### ISSUE TITLE
Power Bi - cannot convert record to table error

### ISSUE THREAD

**Issue by learnTech** [TheAlphaSchoolSystemPTYLTD/lms-integration#13]
Expression.Error: We cannot convert a value of type Record to type Table.
Details:
    Value=
        code=ALL
        timestamp={ts '2022-05-30 09:32:33'}
        lmsflag=Y
    Type=[Type]

any suggestions?

**Comment by leonseremelis-tass** [comment]
It appears that the issue you're facing is related to Power BI rather than the API itself. Unfortunately, we are unable to provide direct assistance in this particular case. We recommend reaching out to Power BI support or consulting their documentation for guidance on resolving the issue.
