### ISSUE TITLE
Can getStudentTimetable return attribute names in lower case in the next version of API?

### ISSUE THREAD

**Issue by team-hq** [TheAlphaSchoolSystemPTYLTD/lms-integration#14]
The API is using lower case everywhere, but then you hit this method and everything is in upper case. It's a bit annoying having to convert things to lower case to reuse the same matching code.

Cheers,

M

**Comment by leonseremelis-tass** [comment]
Thank you for your inquiry. We are actively working towards standardizing our APIs in the future.
