### ISSUE TITLE
Documentation refers to wrongly named variable

### ISSUE THREAD

**Issue by Matatsuo** [TheAlphaSchoolSystemPTYLTD/lms-integration#15]
https://github.com/TheAlphaSchoolSystemPTYLTD/lms-integration/blob/master/getTimetables.md

Get timetables says

> Required:
> 
> year_num [string] - Year Number
> 
> period [string] - Period Code

Then the example has

> { 
>     "year":"2020",
>     "period":"2"
>   }

please correct accordingly.

**Comment by tassweb-talon** [comment]
already done
