### ISSUE TITLE
We need a way to connect subjects to faculties

### ISSUE THREAD

**Issue by team-hq** [TheAlphaSchoolSystemPTYLTD/lms-integration#17]
I'm building a catchup exam form for a client and would like to get the faculty automatically when the student selects the subject. But TASS API doesn't provide a link between subjects and faculties. I believe that TASS refers to them as "departments". I can see that a teacher method getTeachers.md contains the comma separated departments, so I can tie teachers to faculties and I can tie subject to students, but there's no way to link subjects to faculties. Am I missing something? 

Thank you for your help in advance!

**Comment by leonseremelis-tass** [comment]
Thank you for reaching out to us. We appreciate your query and will evaluate this feature internally. We will carefully consider its potential and provide you with a timely response.

**Comment by scottetass** [comment]
Hi,

getTeacherSubjects has been modified to include the subject department code and description.

```
        {
            "sub_code": "ANCH20",
            "sub_short": "AnHist",
            "sub_long": "Ancient History",
            "class": "A",
            "employee_code": 1000016,
            "sub_type": "COR",
            "teacher_code": "AJ",
            "semester": 2,
            "year_grp_desc": 8,
            "year_grp": 8,
            "year_num": 2023,
            "sub_dept_code": "SOC",
            "sub_dept_desc": "Social Sciences Department",
            "sub_desc": "Ancient History"
        }
```

This will be in the May Release.

Thanks, Scott
