### ISSUE TITLE
getSubjects API call

### ISSUE THREAD

**Issue by jonathan-bird** [TheAlphaSchoolSystemPTYLTD/lms-integration#19]
I see that you guys offer a `getStudentSubjects` API call that I can call which gets all students, and all subjects associated with those students, however it'd be great to have a specific `getSubjects` API call similar to your `getStudents` one which means I can save that data first, and then save the student <> subject associations second.

Is this currently possible?

**Comment by scottetass** [comment]
Hi Jonathan,

There is no scope for doing this at this time but it will be considered for our new API offering, which is due for initial release later in the year.

Regards, Scott
