### ISSUE TITLE
getTeacherTimetables start_at and end_at values

### ISSUE THREAD

**Issue by cwool** [TheAlphaSchoolSystemPTYLTD/lms-integration#7]
When testing the timetable report that start_at and end_at values are empty (year 1900) for lessons. Although the report is completing successfully and data are being inserted in the db, I am not sure what the impact will be having these fields empty.

Just wondering if you have any suggestions? ￼  We are using the getTeacherTimetables and we are using these fields to map to our lesson table as these are the only datetime fields in the API response.

![Rex-2020-09-08 18 41 18 (1)](https://user-images.githubusercontent.com/70622121/92860676-de6aa400-f43b-11ea-99a7-304860253f05.png)

Just not sure if it’s because it’s just test data so the dates look like that - in which case should be fine. Otherwise, we need to find the date range somewhere else (e.g. maybe calculation is required).

**Comment by bradftass** [comment]
Hi, apologies for the delay in responding.  The values returned for "prd_end" and "prd_start" are accurate.  They are designed to return the time values for the period only, not the actual date of the period (the 1900 date is a filler for the database).  I hope this helps.
